'use client';

import Link from 'next/link';
import { useState } from 'react';
import { format } from 'date-fns';
import toast from 'react-hot-toast';
import { createClient } from '@/lib/supabase/client';
import { Match, Profile, RatingEvent } from '@/lib/types';
import { useStore } from '@/store/useStore';
import { useDatabaseRefresh } from '@/lib/use-database-refresh';
import InstallAppHint from '@/components/InstallAppHint';

export default function ProfileClient({ profile, matches, ratingEvents, rank, currentUserId }: { profile: Profile; matches: Match[]; ratingEvents: RatingEvent[]; rank: number; currentUserId: string }) {
  useDatabaseRefresh(`profile-${profile.id}`);
  const supabase=createClient();const {setUser}=useStore();const [loading,setLoading]=useState(false);const mine=profile.id===currentUserId;
  const rate=profile.total_wins+profile.total_losses?Math.round(profile.total_wins/(profile.total_wins+profile.total_losses)*100):0;
  const challenge=async()=>{setLoading(true);try{const r=await fetch('/api/challenges',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({opponent_id:profile.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);toast.success('Challenge sent!');}catch(e){toast.error(e instanceof Error?e.message:'Could not send challenge');}finally{setLoading(false);}};
  const logout=async()=>{await supabase.auth.signOut();setUser(null);window.location.href='/';};
  return <main className="min-h-screen bg-accent-gray-50 px-4 py-7"><div className="mx-auto max-w-4xl space-y-7"><section className="rounded-3xl gradient-purple p-6 text-white shadow-xl"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-white/20 text-2xl font-black">{profile.display_name[0].toUpperCase()}</div><div className="min-w-0"><h1 className="truncate text-3xl font-black">{profile.display_name}</h1><p className="text-sm text-white/70">Member since {format(new Date(profile.created_at),'MMM yyyy')}</p></div></div><div className="mt-6 grid grid-cols-3 gap-2 text-center"><div><p className="text-3xl font-black">#{rank}</p><p className="text-xs text-white/70">Rank</p></div><div><p className="text-3xl font-black">{profile.current_elo}</p><p className="text-xs text-white/70">ELO</p></div><div><p className="text-3xl font-black">{profile.highest_elo}</p><p className="text-xs text-white/70">Peak</p></div></div></section>
    {mine&&<InstallAppHint />}
    {!mine&&<section className="grid grid-cols-2 gap-3"><Link href={`/play/record?opponent=${profile.id}`} className="flex min-h-14 items-center justify-center rounded-2xl border-2 border-primary-purple bg-white font-black text-primary-purple">Record Match</Link><button onClick={challenge} disabled={loading} className="min-h-14 rounded-2xl gradient-purple font-black text-white disabled:opacity-50">{loading?'Sending…':'Challenge'}</button></section>}
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[{label:'Record',value:`${profile.total_wins}-${profile.total_losses}`},{label:'Win rate',value:`${rate}%`},{label:'Streak',value:profile.current_streak>0?`W${profile.current_streak}`:profile.current_streak<0?`L${Math.abs(profile.current_streak)}`:'—'},{label:'Best streak',value:`W${profile.longest_streak}`}].map(s=><div key={s.label} className="rounded-2xl bg-white p-4 text-center shadow-sm"><p className="text-2xl font-black">{s.value}</p><p className="text-xs font-bold text-accent-gray-500">{s.label}</p></div>)}</section>
    <section><h2 className="mb-3 text-xl font-black">Recent matches</h2><div className="space-y-3">{matches.map(match=>{const one=match.player_one_id===profile.id;const opponent=one?match.player_two:match.player_one;const oneScore=match.player_one_score??0;const twoScore=match.player_two_score??0;const won=match.winner_id===profile.id||(match.winner_id==null&&(one?oneScore>twoScore:twoScore>oneScore));const myScore=one?oneScore:twoScore;const theirScore=one?twoScore:oneScore;const change=one?match.player_one_elo_change:match.player_two_elo_change;return <Link href={`/match/${match.id}`} key={match.id} className="grid grid-cols-[3.2rem_1fr_auto] items-center gap-3 rounded-2xl bg-white p-4 shadow-sm"><span className={`font-black ${won?'text-green-600':'text-red-600'}`}>{won?'WIN':'LOSS'}</span><span><span className="block font-black">vs {opponent?.display_name}</span><span className="text-sm text-accent-gray-500">{myScore}–{theirScore} · {match.confirmed_at?format(new Date(match.confirmed_at),'MMM d'):''}</span></span><span className={`font-black ${(change||0)>=0?'text-green-600':'text-red-600'}`}>{(change||0)>=0?'+':''}{change||0}</span></Link>;})}{!matches.length&&<div className="rounded-2xl bg-white p-8 text-center text-accent-gray-500">Play your first ranked match.</div>}</div></section>
    <section><h2 className="mb-3 text-xl font-black">Rating history</h2><div className="space-y-2">{ratingEvents.map(event=><div key={event.id} className="flex items-center justify-between rounded-2xl bg-white p-4"><span><span className="block font-bold">{event.rating_before} → {event.rating_after}</span><span className="text-sm text-accent-gray-500">{format(new Date(event.created_at),'MMM d, yyyy')}</span></span><span className={`text-xl font-black ${event.rating_change>=0?'text-green-600':'text-red-600'}`}>{event.rating_change>=0?'+':''}{event.rating_change}</span></div>)}</div></section>
    {mine&&<button onClick={logout} className="min-h-12 w-full rounded-2xl border-2 border-red-200 font-bold text-red-600">Log out</button>}
  </div></main>;
}
